# Generated by Django 6.1 on 2026-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0002_alter_wifidevice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifisubscription',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
