# Generated by Django 6.1 on 2026-09-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0004_branch_mikrotikdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_users', models.IntegerField(default=0)),
                ('cpu_load', models.FloatField(default=0.0)),
                ('free_memory', models.BigIntegerField(default=0)),
                ('total_memory', models.BigIntegerField(default=0)),
                ('uptime', models.CharField(blank=True, max_length=50)),
                ('rx_rate', models.FloatField(default=0.0)),
                ('tx_rate', models.FloatField(default=0.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='wifi.mikrotikdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='wifi_device_device__9bf19e_idx')],
            },
        ),
    ]
