# Generated by Django 6.1 on 2026-09-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi', '0005_devicemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemetric',
            name='rx_byte',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicemetric',
            name='tx_byte',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wifisubscription',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
